# Generated by Django 2.2.1 on 2019-05-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('primary_muscle', models.IntegerField(choices=[(1, 'Chest'), (2, 'Back'), (3, 'Abs'), (4, 'Quad'), (5, 'Triceps'), (6, 'Biceps'), (7, 'Calves'), (8, 'Hamstrings'), (9, 'Trapezius')], default=1)),
                ('secondary_muscle', models.IntegerField(choices=[(1, 'Chest'), (2, 'Back'), (3, 'Abs'), (4, 'Quad'), (5, 'Triceps'), (6, 'Biceps'), (7, 'Calves'), (8, 'Hamstrings'), (9, 'Trapezius')], default=1)),
                ('additional_muscle', models.IntegerField(choices=[(1, 'Chest'), (2, 'Back'), (3, 'Abs'), (4, 'Quad'), (5, 'Triceps'), (6, 'Biceps'), (7, 'Calves'), (8, 'Hamstrings'), (9, 'Trapezius')], default=1)),
            ],
        ),
    ]
